### ISSUE TITLE
please CakeDC/Migration file

### ISSUE THREAD

**Issue by tarky** [aschelch/cakephp-notification-plugin#1]
Please provide schema information by CakeDC/Migration file.
Many CakePHP users manage schema by CakeDC/Migration plugin.
I think it's easier.

**Comment by aschelch** [comment]
Hi, Okay i will do that ;)

**Comment by tarky** [comment]
Thanks a lot!

**Comment by matteo1970** [comment]
Hi, i've installed your pligin but it returned this error:

<b>Fatal error</b>:  Uncaught exception 'FatalErrorException' with message '[MissingHelperException] Helper class NotificationHelper could not be found.
#0 C:\wamp\www\adminpanel\lib\Cake\View\HelperCollection.php(63): HelperCollection-&gt;load('Notification')
#1 C:\wamp\www\adminpanel\lib\Cake\View\View.php(858): HelperCollection-&gt;__isset('Notification')
#2 C:\wamp\www\adminpanel\admin\View\Elements\Default\header.ctp(3): View-&gt;__get('Notification')
#3 C:\wamp\www\adminpanel\lib\Cake\View\View.php(971): include('C:\wamp\www\adm...')
#4 C:\wamp\www\adminpanel\lib\Cake\View\View.php(933): View-&gt;_evaluate('C:\wamp\www\adm...', Array)
#5 C:\wamp\www\adminpanel\lib\Cake\View\View.php(1224): View-&gt;_render('C:\wamp\www\adm...', Array)
#6 C:\wamp\www\adminpanel\lib\Cake\View\View.php(418): View-&gt;_renderElement('C:\wamp\www\adm...', Array, Array)
#7 C:\wamp\www\adminpanel\admin\View\Layouts\error.ctp(32): View-&gt;element('Default/header')
#8 C:\wamp\www\adminpanel\lib\Cake\View\View.php(971): include('C:\wamp\www\adm...')
#9 C: in <b>C:\wamp\www\adminpanel\lib\Cake\Error\ErrorHandler.php</b> on line <b>138</b><br />

can u help me please?
Thanks

**Comment by aschelch** [comment]
Did you add the `public $helper = array('Notification.Notification');` in your controller ?
